"""add_user_comments_to_rfq

Revision ID: add_user_comments_to_rfq
Revises: add_apd_field_to_rfq
Create Date: 2024-01-01 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_user_comments_to_rfq"
down_revision = "add_apd_field_to_rfq"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rfqs", sa.Column("user_comments", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rfqs", "user_comments")
    # ### end Alembic commands ###
