-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
ALTER TABLE IF EXISTS public."General_Purchase_RFQ" DROP CONSTRAINT IF EXISTS creator_user;
ALTER TABLE IF EXISTS public."General_Purchase_RFQ" DROP CONSTRAINT IF EXISTS approver_user;
ALTER TABLE IF EXISTS public."General_Purchase_RFQ" DROP CONSTRAINT IF EXISTS site_code;
ALTER TABLE IF EXISTS public.users DROP CONSTRAINT IF EXISTS user_site;
ALTER TABLE IF EXISTS public."Service_Items_Quotation" DROP CONSTRAINT IF EXISTS rfq_details;
ALTER TABLE IF EXISTS public."Service_Items_Quotation" DROP CONSTRAINT IF EXISTS vendor_details;
ALTER TABLE IF EXISTS public."Service_Items_Quotation" DROP CONSTRAINT IF EXISTS service_items_details;
ALTER TABLE IF EXISTS public."Transport_Items_Quotation" DROP CONSTRAINT IF EXISTS rfq_details;
ALTER TABLE IF EXISTS public."Transport_Items_Quotation" DROP CONSTRAINT IF EXISTS vendor_details;
ALTER TABLE IF EXISTS public."Transport_Items_Quotation" DROP CONSTRAINT IF EXISTS transport_items_details;
ALTER TABLE IF EXISTS public."Indent_Items_Quotation" DROP CONSTRAINT IF EXISTS rfq_details;
ALTER TABLE IF EXISTS public."Indent_Items_Quotation" DROP CONSTRAINT IF EXISTS indent_items_details;
ALTER TABLE IF EXISTS public."Indent_Items_Quotation" DROP CONSTRAINT IF EXISTS item_vendor;
ALTER TABLE IF EXISTS public."Attachments" DROP CONSTRAINT IF EXISTS attachment_rfq;
ALTER TABLE IF EXISTS public."Attachments" DROP CONSTRAINT IF EXISTS attachment_vendor;
ALTER TABLE IF EXISTS public."RFQ_Vendors" DROP CONSTRAINT IF EXISTS rfq_id_main;
ALTER TABLE IF EXISTS public."RFQ_Vendors" DROP CONSTRAINT IF EXISTS vendors_ids;
DROP TABLE IF EXISTS public."General_Purchase_RFQ";
CREATE TABLE IF NOT EXISTS public."General_Purchase_RFQ" (
    id uuid,
    rfq_number character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    description character varying,
    commodity_type "COMMODITY_TYPES",
    status "RFQ_STATUS",
    total_value bigint,
    currency character varying,
    apd_number character varying,
    creator_comments character varying,
    approver_comments character varying,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    created_by uuid,
    approved_by uuid,
    sitewise_id bigint,
    site_code character varying,
    PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public."General_Purchase_RFQ" ENABLE ROW LEVEL SECURITY;
DROP TABLE IF EXISTS public."Indent_Items";
CREATE TABLE IF NOT EXISTS public."Indent_Items" (
    id uuid,
    "itemCode" character varying(50) NOT NULL,
    description character varying(500) NOT NULL,
    specification character varying NOT NULL,
    "UOM" character varying(20) NOT NULL,
    "isActive" boolean NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    quantity bigint,
    last_buying_price bigint,
    last_vendor_name character varying,
    PRIMARY KEY (id, "itemCode")
);
COMMENT ON TABLE public."Indent_Items" IS 'Indent Items with prefilled inforamtaion';
DROP TABLE IF EXISTS public.users;
CREATE TABLE IF NOT EXISTS public.users (
    id uuid NOT NULL,
    username character varying,
    email character varying,
    password character varying,
    first_name character varying,
    last_name character varying,
    role "USER_ROLES",
    is_active boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    site_id uuid,
    PRIMARY KEY (id)
);
COMMENT ON TABLE public.users IS 'user details';
DROP TABLE IF EXISTS public."Service_Items_Quotation";
CREATE TABLE IF NOT EXISTS public."Service_Items_Quotation" (
    id uuid,
    rfq_id uuid,
    service_items_id uuid,
    vendors_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS public."Transport_Items_Quotation";
CREATE TABLE IF NOT EXISTS public."Transport_Items_Quotation" (
    id uuid,
    rfq_id uuid,
    transport_items_id uuid,
    vendors_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS public."Indent_Items_Quotation";
CREATE TABLE IF NOT EXISTS public."Indent_Items_Quotation" (
    id uuid,
    rfq_id uuid,
    indent_items_id uuid,
    vendor_id uuid,
    transportation_freight bigint,
    packaging_charges bigint,
    delivery_lead_time character varying,
    warranty character varying,
    currency character varying(3),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS public.vendors;
CREATE TABLE IF NOT EXISTS public.vendors (
    id uuid,
    name character varying NOT NULL,
    code character varying NOT NULL,
    is_active boolean,
    providing_commodity_type character varying NOT NULL,
    contact_person character varying NOT NULL,
    email character varying,
    phone bigint,
    address character varying,
    state character varying,
    country character varying,
    postal_code bigint,
    tax_id character varying,
    gst_number character varying,
    status "SUPPLIER_STATUS",
    rating integer,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS public."Service_Items";
CREATE TABLE IF NOT EXISTS public."Service_Items" (
    id uuid,
    description character varying,
    specification character varying,
    "UOM" character varying,
    quantity bigint,
    rate bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS public."Transport_Items";
CREATE TABLE IF NOT EXISTS public."Transport_Items" (
    id uuid NOT NULL,
    "from" character varying NOT NULL,
    "to" character varying NOT NULL,
    vehicle_size character varying NOT NULL,
    load bigint NOT NULL,
    frequency bigint NOT NULL,
    dimensions character varying NOT NULL,
    suggestions character varying,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS public."Attachments";
CREATE TABLE IF NOT EXISTS public."Attachments" (
    id uuid,
    rfq_id uuid,
    vendor_id uuid,
    attachement_type text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS public."RFQ_Vendors";
CREATE TABLE IF NOT EXISTS public."RFQ_Vendors" (
    id uuid,
    rfq_id uuid,
    vendors_ids uuid [],
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS public."Sites";
CREATE TABLE IF NOT EXISTS public."Sites" (
    id uuid,
    code character varying NOT NULL,
    name character varying NOT NULL,
    address character varying NOT NULL,
    is_active boolean NOT NULL,
    last_rfq_sitewise_id bigint NOT NULL,
    contact_name character varying,
    contact_email character varying,
    contact_number bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id, code)
);
ALTER TABLE IF EXISTS public."General_Purchase_RFQ"
ADD CONSTRAINT creator_user FOREIGN KEY (created_by) REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."General_Purchase_RFQ"
ADD CONSTRAINT approver_user FOREIGN KEY (approved_by) REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."General_Purchase_RFQ"
ADD CONSTRAINT site_code FOREIGN KEY (site_code) REFERENCES public."Sites" (code) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.users
ADD CONSTRAINT user_site FOREIGN KEY (site_id) REFERENCES public."Sites" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Service_Items_Quotation"
ADD CONSTRAINT rfq_details FOREIGN KEY (rfq_id) REFERENCES public."General_Purchase_RFQ" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Service_Items_Quotation"
ADD CONSTRAINT vendor_details FOREIGN KEY (vendors_id) REFERENCES public.vendors (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Service_Items_Quotation"
ADD CONSTRAINT service_items_details FOREIGN KEY (service_items_id) REFERENCES public."Service_Items" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Transport_Items_Quotation"
ADD CONSTRAINT rfq_details FOREIGN KEY (rfq_id) REFERENCES public."General_Purchase_RFQ" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Transport_Items_Quotation"
ADD CONSTRAINT vendor_details FOREIGN KEY (vendors_id) REFERENCES public.vendors (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Transport_Items_Quotation"
ADD CONSTRAINT transport_items_details FOREIGN KEY (transport_items_id) REFERENCES public."Transport_Items" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Indent_Items_Quotation"
ADD CONSTRAINT rfq_details FOREIGN KEY (rfq_id) REFERENCES public."General_Purchase_RFQ" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Indent_Items_Quotation"
ADD CONSTRAINT indent_items_details FOREIGN KEY (indent_items_id) REFERENCES public."Indent_Items" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Indent_Items_Quotation"
ADD CONSTRAINT item_vendor FOREIGN KEY (vendor_id) REFERENCES public.vendors (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Attachments"
ADD CONSTRAINT attachment_rfq FOREIGN KEY (rfq_id) REFERENCES public."General_Purchase_RFQ" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."Attachments"
ADD CONSTRAINT attachment_vendor FOREIGN KEY (vendor_id) REFERENCES public.vendors (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."RFQ_Vendors"
ADD CONSTRAINT rfq_id_main FOREIGN KEY (rfq_id) REFERENCES public."General_Purchase_RFQ" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public."RFQ_Vendors"
ADD CONSTRAINT vendors_ids FOREIGN KEY (vendors_ids) REFERENCES public.vendors (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
END;